# Generated by Django 5.2.1 on 2025-05-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_alter_course_creator_alter_lecturer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselecturer',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courseApp.lecturer'),
        ),
    ]
