# Generated by Django 5.2.1 on 2025-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_alter_courselecturer_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('p', 'Professor'), ('a', 'Assistant'), ('d', 'Demonstrator')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
