# Generated by Django 5.2.1 on 2025-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
