# Generated by Django 5.2.1 on 2025-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_alter_band_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='events_attended',
            field=models.IntegerField(default=0),
        ),
    ]
