# Generated by Django 5.2.1 on 2025-05-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'r'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.employee'),
        ),
    ]
