# Generated by Django 5.1.7 on 2025-03-24 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('F', 'Food'), ('D', 'Drink'), ('B', 'Bakery'), ('C', 'Cosmetics'), ('H', 'Hygiene')], max_length=1)),
                ('is_homemade', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_market', models.IntegerField()),
                ('date_created', models.DateField()),
                ('working_time_from', models.TimeField()),
                ('working_time_to', models.TimeField()),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.contactinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=13, unique=True)),
                ('salary', models.DecimalField(decimal_places=1, max_digits=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.market')),
            ],
        ),
        migrations.CreateModel(
            name='MarketProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.product')),
            ],
        ),
    ]
