# Generated by Django 5.2.1 on 2025-05-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='book_photos/')),
                ('isbn', models.CharField(max_length=100)),
                ('year_publishing', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
                ('cover_type', models.CharField(choices=[('S', 'Soft'), ('H', 'Hard')], max_length=1)),
                ('category', models.CharField(choices=[('R', 'Romance'), ('T', 'Thriller'), ('B', 'Biography'), ('C', 'Classics'), ('D', 'Drama'), ('H', 'History')], max_length=1)),
                ('price', models.IntegerField()),
                ('record_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.recordlabel')),
            ],
        ),
    ]
