# Generated by Django 5.2.1 on 2025-05-24 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='real_estates_photos/')),
                ('is_reserved', models.BooleanField()),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('linkedin_link', models.URLField()),
                ('number_sales', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.agent')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.characteristic')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.realestate')),
            ],
        ),
    ]
