# Generated by Django 5.2.1 on 2025-05-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year_of_establishment', models.CharField(max_length=4)),
                ('number_of_employees', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('chassis_number', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year_of_production', models.CharField(max_length=4)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_type', models.CharField(choices=[('SE', 'Sedan'), ('SY', 'SUV'), ('HA', 'Hatchback'), ('CO', 'Coupe')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car_photos/')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentalApp.manufacturer')),
            ],
        ),
    ]
